version: '3.4'

services:
  #machinecartsystem.ui:
  # environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  # ports:
  #    - "4200:4200"

  sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: SqlServer
    environment:
        - SA_PASSWORD=sa@123456
        - ACCEPT_EULA=Y
    ports:
        - "5433:1433"

  gateway.web:
    container_name: Gateway.Web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayUrl=${GatewayUrl}
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identityserver:
    container_name: IdentityServer
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayUrl=${GatewayUrl}
    ports:
      - "2000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - gateway.web

  basket.api:
    container_name: Basket.Api
    environment:    
         - ASPNETCORE_ENVIRONMENT=Development
         - GatewayUrl=${GatewayUrl}
    ports:
      - "2001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - gateway.web

  order.api:
    container_name: Order.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayUrl=${GatewayUrl}
    ports:
      - "2002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - gateway.web

  catalog.api:
    container_name: Catalog.Api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GatewayUrl=${GatewayUrl}
    ports:
      - "2003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - gateway.web