version: '3.4'

services:
  #machinecartsystem.ui:
  # environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  # ports:
  #    - "4200:4200"

  machinecartsystem.gateway.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
