version: '3.4'

services:

  #machinecartsystem.ui:
  #  container_name: MachineCartSystem.UI
  # image: ${DOCKER_REGISTRY-}machinecartsystemui
  #  build:
  #    context: .
  #   dockerfile: MachineCartSystem.UI/Dockerfile

  gateway.web:
    image: ${DOCKER_REGISTRY-}machinecartsystemgatewayweb
    build:
      context: .
      dockerfile: MachineCartSystem.Gateways/MachineCartSystem.WebGateway/MachineCartSystem.Gateway.Web/Dockerfile

  identityserver:
    image: ${DOCKER_REGISTRY-}machinecartsystemidentityserver
    build:
      context: .
      dockerfile: MachineCartSystem.Microservices/Identity/MachineCartSystem.IdentityServer/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}machinecartsystembasketapi
    build:
      context: .
      dockerfile: MachineCartSystem.Microservices/Basket/MachineCartSystem.Basket.Api/Dockerfile

  order.api:
    image: ${DOCKER_REGISTRY-}machinecartsystemorderapi
    build:
      context: .
      dockerfile: MachineCartSystem.Microservices/Order/MachineCartSystem.Order.Api/Dockerfile
  
  catalog.api:
    image: ${DOCKER_REGISTRY-}machinecartsystemcatalogapi
    build:
      context: .
      dockerfile: MachineCartSystem.Microservices/Catalog/MachineCartSystem.Catalog.Api/Dockerfile
      