version: '3.4'

services:
  #machinecartsystem.ui:
  # environment:
  #    - ASPNETCORE_ENVIRONMENT=Development
  # ports:
  #    - "4200:4200"

  machinecartsystem.sql-server:
    image: mcr.microsoft.com/mssql/server
    container_name: MachineCartSystem.SqlServer
    environment:
        - SA_PASSWORD=sa@123456
        - ACCEPT_EULA=Y
    ports:
        - "5433:1433"

  machinecartsystem.gateway.web:
    #container_name: MachineCartSystem.Gateway.Web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  machinecartsystem.basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2001:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - machinecartsystem.gateway.web

  machinecartsystem.order.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2002:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - machinecartsystem.gateway.web

  machinecartsystem.catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "2003:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - machinecartsystem.gateway.web